name: cashmoney
version: 0.1.0.0
github: "astralbijection/cashmoney"
license:  AGPL-3.0-only
author: "Astrid Yu"
maintainer: "Astrid Yu"
copyright: "2021 Astrid Yu"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/astralbijection/cashmoney#readme>

dependencies:
  - base >= 4.7 && < 5
  - time
  - filepath
  - text
  - text-format
  - Glob
  - bytestring
  - vector
  - cassava
  - containers

default-extensions:
  - DeriveGeneric
  - OverloadedStrings
  - NamedFieldPuns

library:
  source-dirs: src

executables:
  cashmoney-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cashmoney

tests:
  cashmoney-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cashmoney
      - hspec
